buildscript {
    repositories {
        maven { url = uri("local-maven-repo") }   // <-- فایل‌های AGP که دستی کپی کردیم
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://mirror-maven.runflare.com/repository/public/' }
        maven { url 'https://maven.myket.ir' }
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
    }
}

allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://mirror-maven.runflare.com/repository/public/' }
        maven { url 'https://maven.myket.ir' }
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
